### ISSUE TITLE
Feature Request: Don't wait for input to finish before printing

### ISSUE THREAD

**Issue by exoji2e** [theryangeary/choose#10]
Hi! Cool project, very nice alternative to `awk`/`cut`.

It would be nice to be able to use `choose` on an endless stream, passing on output as new lines arrives on stdin. Some examples:

`ping 8.8.8.8 | choose -2 | choose -f "=" 1`
`tail -f log.log | choose 0`

Of course using the approach of printing the match after each line is highly inefficient working on files. Maybe it could be a setting `--release-output` which by default is not used when reading files, but used when reading from `stdin`?

**Comment by theryangeary** [comment]
Hi @exoji2e I agree, this is one of the things I've been thinking needs some work. Ideally without any need for a flag or switch. Stay tuned.

**Comment by theryangeary** [comment]
As an update, I believe this will take some async/await or tokio code but I don't know too much about that. It will happen eventually but I don't exactly how long it will take to get there. I don't think it should take too much work I just need to better understand async.

**Comment by theryangeary** [comment]
Merged in develop
