### ISSUE TITLE
Exclusivity / inclusivity problems

### ISSUE THREAD

**Issue by omertuc** [theryangeary/choose#13]
I've come across several issues with inclusivity / exclusivity:

# readme mistake
The `readme.md` says:
 ```
choose :3              # print the beginning of the line to the 3rd item,
                        # exclusive
```

Which I take to mean that the item with index 3 won't be included when `:3` is used, i.e:
`echo 0 1 2 3 | choose :3` should output `0 1 2`. However, it outputs `0 1 2 3`. Is the `readme.md` wrong? Did you intend to add a `-x` there and forgot? Or is that a bug?

# python-like 
Claiming `choose` is Python like and then requiring `-x` for exclusivity is wrong in my opinion, to aim to be more Python-like, `choose` should be exclusive by default.

## Python:
```
In [1]: [0,1,2,3][:3]
Out[1]: [0, 1, 2]
```
## Choose:
```
$ echo 0 1 2 3 | choose :3
0 1 2 3
```

# Empty results when using `-x`
Since I want `choose` to be more Python-like, I created an alias `alias c='choose -x'` so it's always exclusive by default. However, when I try to use it like this:
```
$ echo 0 1 2 3 | c 2


```
Nothing is output, as shown.

What do you think?

**Comment by theryangeary** [comment]
# readme mistake
You're right, this is a typo on my part.
# python-like
Yes, admittedly this is not 100% the way python list slices work. Originally exclusivity was default but I found that over and over as I developed and used `choose` that my mind would assume inclusivity and I wanted to provide defaults that would be commonly appreciated. **I plan on adding the ability to specify exclusivity with an environment variable**, which it seems you will appreciate given your alias.
# empty results when using `-x`
Astute observation, you have indeed uncovered a bug.

**I am going to open separate issues for each of these items.**

**Comment by omertuc** [comment]
Cool, thanks for the quick response.

Regarding the difference from the Python behavior - I think it would be nice if this was explicitly mentioned in the README. Either the exact difference or just mentioning that it's "mostly like-python".

Regarding the env variable - I'm actually personally against an environment variable for exclusivity. It might cause confusion/surprising behavior since it is usually hidden from view - an explicit, visible flag is essential in this case (my alias is an exception to that idea because I only use it in my personal command line / scripts).

**Comment by theryangeary** [comment]
I think that the environment variable would effectively achieve the same result as your alias. This would be something that should be set in one's shell rc, NOT in one's profile, so it would apply to a shell but not to your whole environment, so if it were used in a script it wouldn't apply. 

That being said, I don't think this tool should be used in scripts (bar trivial ones, *maybe*), just as you wouldn't use `rg` over `grep` or `bat` over `cat` in a script.

**Comment by omertuc** [comment]
> I think that the environment variable would effectively achieve the same result as your alias. This would be something that should be set in one's shell rc, NOT in one's profile, so it would apply to a shell but not to your whole environment, so if it were used in a script it wouldn't apply.

Fair enough. 

> That being said, I don't think this tool should be used in scripts (bar trivial ones, _maybe_), just as you wouldn't use `rg` over `grep` or `bat` over `cat` in a script.

For now yes, but when Rust takes over the world and replaces all basic unix tools with their Rust equivalents, you'll regret this decision! /s

**Comment by theryangeary** [comment]
Perhaps someday my friend. And on that day we will probably determine if we are being invoked from a script or a terminal and ignore env vars accordingly! :crab:
