### ISSUE TITLE
Brew package?

### ISSUE THREAD

**Issue by erkac** [theryangeary/choose#21]
Hi,

although the compile process went smooth on my **macOS**, is there any chance to push this as the **brew** package? The installation would be much easier...

Thanks,
Lubos

**Comment by theryangeary** [comment]
Sure. Do note it can also be installed from cargo now.

I don't have any experience with brew. Do I need a macOS in order to create
a package for it? If so would you be willing to lend a hand?

**Comment by theryangeary** [comment]
assigning to @crclark96

**Comment by erkac** [comment]
My understanding is, that brew is also available for Linux... but yes I'm willing to help with building it... though no experience yet.

**Comment by crclark96** [comment]
https://github.com/Homebrew/homebrew-core/pull/56851

will keep you updated
