### ISSUE TITLE
Request: flag for 1-indexing

### ISSUE THREAD

**Issue by AndydeCleyre** [theryangeary/choose#23]
`choose` helpfully offers compatibility with Python's style of 0-indexing, inclusive start, and exclusive end, with `-x` (which the docs make _sound_ like it uses an exclusive range, while it uses an _inclusive_ start):

```console
$ s=(1 2 3 4 5 6)
$ print $s | choose 2:4
3 4 5
$ print $s | choose -x 2:4
3 4
```

But when I'm in a shell, using ZSH tools, `cut`, etc., I expect 1-indexing, inclusive start, inclusive end:

```console
$ s=(1 2 3 4 5 6)
$ print $s[2,4]
2 3 4
$ print $s | cut -d' ' -f2-4
2 3 4
```

Since the context I'd use `choose` in is the same I'd use ZSH and `cut` in, it would lessen the mental load and chance of user error if I could get it to match the indexing and slicing of ZSH (default config) and `cut`.

Here's the same data as a table, where `s` is an array of the numbers `1` through `6`:

Context | Command | Result | Index | Start | End
--- | --- | --- | --- | --- | ---
`python` | `s[2:4]` | `(3, 4)` | `0` | Inclusive | Exclusive
`zsh` | `print $s[2,4]` | `2 3 4` | `1` | Inclusive | Inclusive
`cut` | `print $s \| cut -d' ' -f2-4` | `2 3 4` | `1` | Inclusive | Inclusive
`choose` | `print $s \| choose 2:4` | `3 4 5` | `0` | Inclusive | Inclusive
`choose` | `print $s \| choose -x 2:4` | `3 4` | `0` | Inclusive | Exclusive

**Comment by theryangeary** [comment]
This is reasonable. I will add it.

**Comment by theryangeary** [comment]
Added in `develop`.
