### ISSUE TITLE
Cannot use newline as an output separator.

### ISSUE THREAD

**Issue by Yamp** [theryangeary/choose#26]
'\n' as output separator doesn't work. It works literally. Other system utilities, like tr, understand that this is newline.

❯ echo "Hello world" | choose : -o '\n'
Hello\nworld

❯ echo "Hello world" | tr ' ' '\n'
Hello
world

**Comment by theryangeary** [comment]
You're right. I'll work on it. There doesn't seem to be an simple/non-manual way to parse a raw string in Rust unfortunately.

**Comment by theryangeary** [comment]
Merged in develop.
