### ISSUE TITLE
musl binary for linux

### ISSUE THREAD

**Issue by elkarouh** [theryangeary/choose#33]
Hi,

I work on quite old linux machines and it is not possible to install anything.
Could you provide musl binaries for linux (in the same way ripgrep and fd do)

Many thanks

**Comment by theryangeary** [comment]
Hi, thanks for the suggestion. I will look into it. In the meantime, I recommend installing the rust toolchain (it's very easy, all you have to do is `curl https://sh.rustup.rs -sSf | sh`), and building with the `musl` target, which you can find more info about here: https://doc.rust-lang.org/edition-guide/rust-2018/platform-and-target-support/musl-support-for-fully-static-binaries.html

**Comment by theryangeary** [comment]
Hi @elkarouh, I've added a [musl build](https://github.com/theryangeary/choose/releases/download/v1.3.1/choose-x86_64-unknown-linux-musl) under the [1.3.1 release]. From my testing, it looks like it works alright, but I'd appreciate it if you would pull it down and take it for a test drive as well.

I plan on updating GitHub actions to build a musl release in an automated fashion going forwards, and I'll leave this ticket open until that is resolved.

**Comment by elkarouh** [comment]
Awesome, thanks!

**Comment by theryangeary** [comment]
I've added a github action to automatically build a musl binary when a new release is made. There is a musl binary in the new 1.3.2 release. Closing now. Thanks for the suggestion!
