### ISSUE TITLE
Error message after existing `less`

### ISSUE THREAD

**Issue by hntee** [theryangeary/choose#34]
Issue environment:

If I open a rather long file with many lines,

`cat file | choose 0 | less`

after existing `less`, choose will print out the error message with many 
`Failed to write to output: Broken pipe (os error 32)`

**Comment by theryangeary** [comment]
Hi @hntee, thanks for reporting this. I am looking into it.

**Comment by theryangeary** [comment]
@hntee I believe I have resolved the issue. Would you be willing to check out the code on the #35 pull request and verify that it works for you as well?
If you need help checking out the branch or building from source, I'm more than happy to guide you through it.

**Comment by hntee** [comment]
Hi @theryangeary,
I have checked out the code and built a version of that.
I think now it can work perfectly, thank you for the great tool!

**Comment by theryangeary** [comment]
This fix is now merged into develop and master, and released in version 1.3.2. Closing. Thanks for the bug report and the help!
