### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by The-King-of-Toasters** [theryangeary/choose#4]
I'd like to package this for the [AUR](https://wiki.archlinux.org/index.php/Arch_User_Repository), but since the project has no license it makes it hard for me to do so.

Personally, I'd recommend something like the ISC or MIT license.

**Comment by theryangeary** [comment]
You're right. I've added a GPLv3 license. It would be awesome to see `choose` in the AUR!

**Comment by joshtriplett** [comment]
`Cargo.toml` has a field for this: could you add `license = "GPL-3.0-or-later"` in your `Cargo.toml`, which software will be able to easily parse?

**Comment by theryangeary** [comment]
Done! (https://github.com/theryangeary/choose/commit/18b3440bec426e692da16561e71c3dbde77541f6)
