### ISSUE TITLE
[Request] Support Escape Character

### ISSUE THREAD

**Issue by spearkkk** [theryangeary/choose#40]
Hi, Im appreciate your nice works.
I just want to request new feature.
Could you support escape character?
For example:
 - I want to set `--field-separator` as `,` for `.csv` file.
 - But there is escaped data, like `"hello, this is me","123",smaple`.

I want to choose first field: `hello, this is me` but i got a just `hello`.

Thank you.

**Comment by theryangeary** [comment]
Hi @spearkkk, thanks for the suggestion. I am going to mull this over and think about the implications. I think it can probably be added without issue, but will probably be an opt-in flag. In the meantime, I would suggest not using `choose` for csv file parsing. I would recommend using a dedicated csv parsing tool such as [xsv](https://github.com/BurntSushi/xsv).

**Comment by spearkkk** [comment]
@theryangeary , Thank you for feedback.
And I appreciate your recommend 😄
