### ISSUE TITLE
May have Window Version?

### ISSUE THREAD

**Issue by happydentist** [theryangeary/choose#43]
Nice program!
Can have Window Version?

**Comment by theryangeary** [comment]
Sure, I can work on adding a Windows binary. In the meantime it should be easy to build from source on windows. If that's not the case let me know!

**Comment by pfmoore** [comment]
I just had a go trying to build on Windows, but I can't even check the repo out 🙁 It appears there's a test file `test/choose_-4:-2.txt`, and that's an invalid filename on Windows (the colon is used for drive letters). There's a few other files with colons in the name, too.

I think these files are only used in the `e2e_test.sh` file, which is unfortunate as that doesn't even work on Windows. Would it be possible to rename those files? I could submit a PR, if that would be acceptable, but I'd have to set up a Unix environment to do so...

**Comment by pfmoore** [comment]
FWIW, I managed to extract all the files except the problematic ones from the zip of master that github provides. With that extract, the code builds fine on Windows and passes `cargo test`. So it appears that apart from the test file names, everything else works fine 🙂

**Comment by pfmoore** [comment]
I created #45 to rename the test files to make the repository cloneable on Windows.

**Comment by ggrothendieck** [comment]
I was able to install this on Windows by installing rust and then running `cargo install choose` .

**Comment by theryangeary** [comment]
added a build in the latest release
