### ISSUE TITLE
How to replace awk split

### ISSUE THREAD

**Issue by Fujiwara-Chika** [theryangeary/choose#44]
```
$ identify 11095193_p0.jpg 
11095193_p0.jpg JPEG 1200x1200 1200x1200+0+0 8-bit sRGB 695510B 0.000u 0:00.002
$ identify 11095193_p0.jpg | gawk '{split($3,sizes,"x"); print $1,sizes[1]/sizes[2]}'
11095193_p0.jpg 1
```
I'd like to use `choose` to replace `awk` because the `filename` sometime include whitespace that lead to error, how to rewrite this by `choose`
<img width="840" alt="image" src="https://user-images.githubusercontent.com/44722787/157811898-049e93e0-a0a6-4055-8d64-2b75590412e3.png">

**Comment by theryangeary** [comment]
I would strongly recommend naming your files to not include whitespace. Failing that, add preprocessing at the begining of your pipeline to create a temporarily renamed file or something along those lines. `choose` does not intend to replace all `awk` features.
