### ISSUE TITLE
feature request: align columns

### ISSUE THREAD

**Issue by bergey** [theryangeary/choose#46]
like piping to `column -t`.  I generally pipe aligned input to `choose`, then pipe the output to `column`. This is common enough that I'd like a short option for it, and I imagine others also work this way.   Maybe when passed `-t`?

I'm happy to open a PR if you like this idea.

**Comment by theryangeary** [comment]
hi @bergey, thanks for the suggestion. Unfortunately, this suggestion goes against the unix philosophy of doing one thing and doing it well. `column` already provides great column aligning features, and I recommend you continue using it for that purpose. no need to reinvent the wheel here.
