### ISSUE TITLE
Select field from a multiline

### ISSUE THREAD

**Issue by jcgutier** [theryangeary/choose#51]
Can I select the 'n' field from 'x' line on multiline input ?

Desired example
$ cat demo.txt
This is a
multiline test

$ cat demo.txt | choose 1 {--line 1} # Desired line selection 
test                                                  # Desired output

**Comment by theryangeary** [comment]
Reducing to a particular line is already easy achieved using `sed`:

$ cat demo.txt | sed -n '2p' | choose 1
test

In the spirit of the unix philosophy choose will not reimplement that feature.
