### ISSUE TITLE
Please branch for EPEL 9 on COPR

### ISSUE THREAD

**Issue by nisbet-hubbard** [theryangeary/choose#66]
Could you please branch for the `epel-9-x86_64` chroot?

**Comment by theryangeary** [comment]
Can you elaborate on what that entails? I'm not familiar with EPEL.

**Comment by daniejstriata** [comment]
I've created an EPEL9 repo that contains `choose` here:
https://copr.fedorainfracloud.org/coprs/faramirza/epel9/packages/
You could easily build your own repo and add packages to it from various sources. For choose I added the rpm spec file to my fork. The spec downloads the source from `github.com/theryangeary/choose` and builds it for aarch64 and x86_64. If you directly use my repo, check what it updates first.
