### ISSUE TITLE
build failure on aarch64 - cross-compiling fails due to missing package

### ISSUE THREAD

**Issue by daniejstriata** [theryangeary/choose#70]
I've been creating rpm packages for choose targeting Amazon Linux and EPEL9 for a while now. The latest release added to `.cargo/config.toml` a linker for aarch64 to allow cross-compiling it. This is causing the build on my aarch64 instance to fail though. When I remove that linker from the config the build succeeds. I am not cross-compiling, Fedora COPR has these and other architectures available. aarch64-linux-gnu-gcc is not available to install on Amazon Linux 2023. 

```
  Downloaded libc v0.2.158
   Compiling version_check v0.9.5
   Compiling proc-macro2 v1.0.86
   Compiling unicode-ident v1.0.13
   Compiling libc v0.2.158
   Compiling syn v1.0.109
error: linker `aarch64-linux-gnu-gcc` not found
  |
  = note: No such file or directory (os error 2)

error: could not compile `proc-macro2` (build script) due to previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `syn` (build script) due to previous error
error: could not compile `libc` (build script) due to previous error
error: Bad exit status from /var/tmp/rpm-tmp.8bn7vy (%build)
    Bad exit status from /var/tmp/rpm-tmp.8bn7vy (%build)
```
I've removed the entry from config.toml in my builds to allow the package to build.

**Comment by theryangeary** [comment]
I just published 1.3.6, which removes the .cargo/config linker for your target and instead includes it only in the github workflow. this should fix your problem.
